import { z } from "zod";

const slug = z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
const currency = z.string().regex(/^[A-Z]{3}$/);
const id = z.string().uuid();
const optionalMoney = z
  .string()
  .regex(/^\d+(?:\.\d{1,4})?$/)
  .optional();

export const commercialActionSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("create_supplier"),
    name: z.string().min(2),
    slug,
    supplierType: z.enum([
      "raw_material",
      "packaging",
      "contract_manufacturer",
      "white_label",
      "private_label",
      "testing_laboratory",
      "general_vendor",
      "other",
    ]),
    notes: z.string().optional(),
  }),
  z.object({ type: z.literal("archive_supplier"), id }),
  z.object({
    type: z.literal("create_supplier_product"),
    supplierId: id,
    ingredientId: id,
    name: z.string().min(2),
    packageSize: z.string().regex(/^\d+(?:\.\d+)?$/),
    packageSizeUnit: z.enum([
      "milliliters",
      "liters",
      "us_fluid_ounces",
      "us_gallons",
      "grams",
      "kilograms",
      "ounces_weight",
      "pounds",
      "each",
      "dozen",
      "pack",
      "case",
    ]),
    packageQuantity: z.string().regex(/^\d+(?:\.\d+)?$/),
    packagePrice: optionalMoney,
    currency: currency.optional(),
    source: z.string().optional(),
  }),
  z.object({
    type: z.literal("create_manufacturer"),
    name: z.string().min(2),
    slug,
    manufacturerType: z.enum([
      "custom",
      "contract",
      "white_label",
      "private_label",
      "bulk_blender",
      "supplement",
      "packaging_filling",
      "other",
    ]),
    notes: z.string().optional(),
  }),
  z.object({
    type: z.literal("create_catalog_product"),
    manufacturerId: id,
    name: z.string().min(2),
    notes: z.string().optional(),
  }),
  z.object({
    type: z.literal("create_quote"),
    manufacturerId: id,
    productId: id,
    quoteNumber: z.string().min(1),
    quoteDate: z.string().date(),
    currency,
  }),
  z.object({
    type: z.literal("create_packaging"),
    name: z.string().min(2),
    componentType: z.enum([
      "bottle",
      "jar",
      "pump",
      "dropper",
      "cap",
      "lid",
      "label",
      "box",
      "carton",
      "insert",
      "tamper_seal",
      "shrink_band",
      "pouch",
      "scoop",
      "shaker",
      "shipping_box",
      "protective_fill",
      "other",
    ]),
    sku: z.string().optional(),
  }),
  z
    .object({
      type: z.literal("create_configuration"),
      productId: id,
      formulaVersionId: id.nullable().optional(),
      manufacturerCatalogProductId: id.nullable().optional(),
      name: z.string().min(2),
      fillSize: z.string().regex(/^\d+(?:\.\d+)?$/),
      fillSizeUnit: z.enum([
        "milliliters",
        "liters",
        "us_fluid_ounces",
        "us_gallons",
        "grams",
        "kilograms",
        "ounces_weight",
        "pounds",
        "each",
        "dozen",
        "pack",
        "case",
      ]),
    })
    .refine(
      (v) =>
        Boolean(v.formulaVersionId) !== Boolean(v.manufacturerCatalogProductId),
      "Choose exactly one formula version or catalog product.",
    ),
  z.object({
    type: z.literal("create_document"),
    title: z.string().min(2),
    documentType: z.enum([
      "certificate_of_analysis",
      "safety_data_sheet",
      "technical_data_sheet",
      "ifra_certificate",
      "allergen_statement",
      "organic_certificate",
      "ingredient_specification",
      "packaging_specification",
      "technical_drawing",
      "supplier_agreement",
      "manufacturer_agreement",
      "nda",
      "quote",
      "invoice",
      "formula_record",
      "test_report",
      "label_file",
      "product_artwork",
      "batch_record",
      "supplement_facts",
      "product_catalog",
      "sample_evaluation",
      "other",
    ]),
    fileName: z.string().min(1),
    storageKey: z.string().min(1),
    mimeType: z.string().min(1),
    fileSize: z.number().int().nonnegative(),
  }),
  z.object({
    type: z.literal("create_cost_scenario"),
    finishedProductConfigurationId: id,
    name: z.string().min(2),
    description: z.string().optional(),
    scenarioDataJson: z.record(z.string(), z.unknown()),
  }),
  z.object({
    type: z.literal("select_supplier_product"),
    formulaVersionId: id,
    formulaIngredientId: id,
    ingredientId: id,
    supplierProductId: id,
    selectionType: z.enum([
      "preferred",
      "alternate",
      "testing",
      "emergency_backup",
      "historical",
    ]),
    preferred: z.boolean().default(false),
    approvedForProduction: z.boolean().default(false),
    notes: z.string().optional(),
  }),
  z.object({
    type: z.literal("link_manufacturer_candidate"),
    productId: id,
    manufacturerId: id,
    manufacturerCatalogProductId: id.nullable().optional(),
    candidateType: z.enum([
      "white_label",
      "private_label",
      "custom_formula",
      "bulk_blending",
      "packaging_filling",
      "alternate_manufacturer",
    ]),
  }),
  z.object({
    type: z.literal("add_quote_line"),
    manufacturerQuoteId: id,
    lineItemType: z.enum([
      "setup",
      "formula_review",
      "sample",
      "raw_materials",
      "blending",
      "manufacturing",
      "testing",
      "filling",
      "container",
      "closure",
      "label",
      "carton",
      "packaging",
      "shipping",
      "storage",
      "other",
    ]),
    description: z.string().min(1),
    quantity: z.string().regex(/^\d+(?:\.\d+)?$/),
    unitPrice: optionalMoney,
    totalPrice: z.string().regex(/^\d+(?:\.\d{1,4})?$/),
    sortOrder: z.number().int().nonnegative(),
  }),
  z.object({
    type: z.literal("record_packaging_compatibility"),
    primaryComponentId: id,
    secondaryComponentId: id,
    compatibilityType: z.enum([
      "bottle_closure",
      "jar_lid",
      "bottle_label",
      "container_carton",
      "container_seal",
      "other",
    ]),
    status: z.enum([
      "unknown",
      "sample_ordered",
      "testing",
      "confirmed",
      "incompatible",
    ]),
    testedDate: z.string().date().nullable().optional(),
    notes: z.string().optional(),
  }),
  z.object({
    type: z.literal("attach_packaging"),
    finishedProductConfigurationId: id,
    packagingComponentId: id,
    quantityPerFinishedUnit: z.string().regex(/^\d+(?:\.\d+)?$/),
    wastePercent: z
      .string()
      .regex(/^\d+(?:\.\d+)?$/)
      .default("0"),
    required: z.boolean().default(true),
    sortOrder: z.number().int().nonnegative(),
  }),
  z.object({
    type: z.literal("link_document"),
    documentId: id,
    entityType: z.string().min(1),
    entityId: id,
    relationshipType: z.string().min(1),
  }),
  z
    .object({
      type: z.literal("create_readiness_item"),
      productId: id,
      finishedProductConfigurationId: id.nullable().optional(),
      readinessCategory: z.enum([
        "product_brief",
        "formula",
        "ingredients",
        "suppliers",
        "manufacturer",
        "sample_testing",
        "packaging",
        "documentation",
        "costing",
        "pricing",
        "production",
        "labeling",
        "launch",
        "market",
      ]),
      itemName: z.string().min(1),
      itemDescription: z.string().optional(),
      sourceType: z.enum(["system_generated", "user_created"]),
      required: z.boolean().default(true),
      status: z.enum([
        "complete",
        "in_progress",
        "missing",
        "needs_review",
        "blocked",
        "not_applicable",
      ]),
      notApplicableReason: z.string().optional(),
    })
    .refine(
      (v) => v.status !== "not_applicable" || Boolean(v.notApplicableReason),
      "Not applicable requires a reason.",
    ),
]);

export type CommercialAction = z.infer<typeof commercialActionSchema>;
