import { z } from "zod";

import {
  createFormulaFamilySchema,
  createIngredientSchema,
  createProductSchema,
  formulaLineSchema,
  productBriefSchema,
  productPriorities,
  pipelineStatuses,
  updateProductSchema,
  updateIngredientSchema,
} from "./development";

export const developmentActionSchema = z.discriminatedUnion("action", [
  z.object({ action: z.literal("create_product"), data: createProductSchema }),
  z.object({
    action: z.literal("update_product"),
    productId: z.string().uuid(),
    productLineId: z.string().uuid().optional(),
    data: updateProductSchema,
  }),
  z.object({
    action: z.literal("update_product_status"),
    productId: z.string().uuid(),
    pipelineStatus: z.enum(pipelineStatuses),
    expectedUpdatedAt: z.string().datetime().optional(),
  }),
  z.object({
    action: z.literal("update_product_priority"),
    productId: z.string().uuid(),
    priority: z.enum(productPriorities),
    expectedUpdatedAt: z.string().datetime().optional(),
  }),
  z.object({
    action: z.literal("archive_product"),
    productId: z.string().uuid(),
  }),
  z.object({
    action: z.literal("save_product_brief"),
    productId: z.string().uuid(),
    data: productBriefSchema,
  }),
  z.object({
    action: z.literal("add_product_note"),
    productId: z.string().uuid(),
    noteType: z.enum([
      "research",
      "product_idea",
      "sourcing",
      "packaging",
      "testing",
      "launch",
      "market_feedback",
      "general",
    ]),
    title: z.string().trim().min(2).max(160),
    content: z.string().trim().min(2).max(10000),
  }),
  z.object({
    action: z.literal("record_product_decision"),
    productId: z.string().uuid(),
    title: z.string().trim().min(2).max(160),
    decision: z.string().trim().min(2).max(5000),
    reason: z.string().trim().min(2).max(5000),
    evidence: z.string().trim().max(5000).nullable().optional(),
    expectedOutcome: z.string().trim().max(5000).nullable().optional(),
    decisionDate: z.string().date(),
    reviewDate: z.string().date().nullable().optional(),
  }),
  z.object({
    action: z.literal("review_product_decision"),
    decisionId: z.string().uuid(),
    status: z.enum(["recorded", "validated", "reversed", "superseded"]),
    actualOutcome: z.string().trim().max(5000).nullable().optional(),
  }),
  z.object({
    action: z.literal("create_ingredient"),
    data: createIngredientSchema,
  }),
  z.object({
    action: z.literal("update_ingredient"),
    ingredientId: z.string().uuid(),
    data: updateIngredientSchema,
  }),
  z.object({
    action: z.literal("archive_ingredient"),
    ingredientId: z.string().uuid(),
  }),
  z.object({
    action: z.literal("create_formula"),
    data: createFormulaFamilySchema,
  }),
  z.object({
    action: z.literal("duplicate_formula_family"),
    formulaVersionId: z.string().uuid(),
    name: z.string().trim().min(2).max(160),
  }),
  z.object({
    action: z.literal("archive_formula_family"),
    formulaFamilyId: z.string().uuid(),
  }),
  z.object({
    action: z.literal("save_formula_composition"),
    formulaVersionId: z.string().uuid(),
    lines: z.array(formulaLineSchema).min(1),
  }),
  z.object({
    action: z.literal("submit_formula_review"),
    formulaVersionId: z.string().uuid(),
  }),
  z.object({
    action: z.literal("create_formula_version"),
    formulaVersionId: z.string().uuid(),
    changeReason: z.string().trim().min(8).max(1000),
    initialStatus: z.enum(["draft", "experimental"]).default("draft"),
  }),
  z.object({
    action: z.literal("add_production_step"),
    formulaVersionId: z.string().uuid(),
    phase: z.string().trim().min(2).max(120),
    instruction: z.string().trim().min(2).max(5000),
    required: z.boolean().default(true),
    notes: z.string().trim().max(5000).nullable().optional(),
  }),
  z.object({
    action: z.literal("save_production_steps"),
    formulaVersionId: z.string().uuid(),
    steps: z.array(
      z.object({
        phase: z.string().trim().min(2).max(120),
        instruction: z.string().trim().min(2).max(5000),
        required: z.boolean(),
        notes: z.string().trim().max(5000).nullable().optional(),
      }),
    ),
  }),
  z.object({
    action: z.literal("create_experiment"),
    productId: z.string().uuid(),
    formulaVersionId: z.string().uuid(),
    name: z.string().trim().min(2).max(160),
    objective: z.string().trim().min(2).max(5000),
    hypothesis: z.string().trim().min(2).max(5000),
    testBatchSize: z.string().regex(/^\d+(?:\.\d{1,6})?$/),
    testBatchUnit: z.enum(["us_fluid_ounces", "milliliters", "grams"]),
  }),
  z.object({
    action: z.literal("add_observation"),
    experimentId: z.string().uuid(),
    observationType: z.enum([
      "immediate",
      "24_hours",
      "7_days",
      "14_days",
      "30_days",
      "custom",
    ]),
    observedAt: z.string().datetime(),
    colorScore: z.number().int().min(1).max(5).nullable().optional(),
    aromaStrengthScore: z.number().int().min(1).max(5).nullable().optional(),
    absorptionScore: z.number().int().min(1).max(5).nullable().optional(),
    greasinessScore: z.number().int().min(1).max(5).nullable().optional(),
    slipScore: z.number().int().min(1).max(5).nullable().optional(),
    hairFeelScore: z.number().int().min(1).max(5).nullable().optional(),
    beardFeelScore: z.number().int().min(1).max(5).nullable().optional(),
    skinFeelScore: z.number().int().min(1).max(5).nullable().optional(),
    notes: z.string().trim().max(5000).nullable().optional(),
    stainingObserved: z.boolean().nullable().optional(),
    separationObserved: z.boolean().nullable().optional(),
    sedimentObserved: z.boolean().nullable().optional(),
    cloudinessObserved: z.boolean().nullable().optional(),
  }),
  z.object({
    action: z.literal("update_experiment_status"),
    experimentId: z.string().uuid(),
    status: z.enum([
      "planned",
      "in_progress",
      "resting",
      "observation_period",
      "abandoned",
      "archived",
    ]),
  }),
  z.object({
    action: z.literal("complete_experiment"),
    experimentId: z.string().uuid(),
    result: z.enum(["passed", "needs_revision", "failed", "inconclusive"]),
    conclusion: z.string().trim().min(2).max(5000),
    nextChange: z.string().trim().max(5000).nullable().optional(),
  }),
]);

export type DevelopmentAction = z.infer<typeof developmentActionSchema>;
